language: rust
rust:
  - nightly

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/30d95aef09ac81d884bf
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
