[package]

name = "liquid"
version = "0.0.1"
authors = ["Johann Hofmann <mail@johann-hofmann.com>"]
description = "The liquid templating language for Rust"
repository = "https://github.com/cobalt-org/liquid-rust"
readme = "README.md"
keywords = ["liquid", "template", "templating", "language", "filters", "html"]
license = "MIT"

[dependencies]
regex = "0.1.14"
regex_macros = "0.1.8"
