[package]

name = "liquid"
version = "0.1.0"
authors = ["Johann Hofmann <mail@johann-hofmann.com>"]
description = "The liquid templating language for Rust"
repository = "https://github.com/cobalt-org/liquid-rust"
documentation = "https://cobalt-org.github.io/liquid-rust/"
readme = "README.md"
keywords = ["liquid", "template", "templating", "language", "html"]
license = "MIT"

[dependencies]
regex = "0.1.30"
