[package]

name = "liquid"
version = "0.8.4"
authors = ["Johann Hofmann <mail@johann-hofmann.com>"]
description = "The liquid templating language for Rust"
repository = "https://github.com/cobalt-org/liquid-rust"
documentation = "https://cobalt-org.github.io/liquid-rust/"
readme = "README.md"
keywords = ["liquid", "template", "templating", "language", "html"]
license = "MIT"

build = "build.rs"

[dependencies]
regex = "0.1"
lazy_static = "0.1.15"
chrono = "0.2.22"
clippy = {version = "0.0", optional = true}

[build-dependencies]
skeptic = "0.4"

[dev-dependencies]
difference = "0.4"
skeptic = "0.4"

[features]
default=[]
dev=[]
